language: ruby
rvm:
  - ruby-1.9.3
  - ruby-2.0.0
  - ruby-2.1.5
  - ruby-2.2.1
  - jruby
  - rbx-2.4.1
  - rbx-2.5.2
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - openjdk6
allow_failures:
  - jruby
  - rbx-2.4.1
  - rbx-2.5.2
before_install: gem install bundler -v 1.10.5
sudo: false